# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "SPEAKERS" ("name" VARCHAR NOT NULL,"bio" VARCHAR NOT NULL,"twitterId" VARCHAR NOT NULL,"id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY);
create table "TALKS" ("description" VARCHAR NOT NULL,"sessionType" INTEGER NOT NULL,"tags" VARCHAR NOT NULL,"speakerId" BIGINT NOT NULL,"id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY);
alter table "TALKS" add constraint "SUP_FK" foreign key("speakerId") references "SPEAKERS"("id") on update NO ACTION on delete NO ACTION;

# --- !Downs

alter table "TALKS" drop constraint "SUP_FK";
drop table "SPEAKERS";
drop table "TALKS";

